# Language setting http://docs.shippable.com/ci/languages/node/
language: node_js

# use this to control what branches get built.
# http://docs.shippable.com/ci/advancedOptions/branches/
branches:
  only:
    - master

# using pre-defined build variables
# full list http://docs.shippable.com/ci/advancedOptions/environmentVariables/
env:
  global:
    - TEST_RESULTS_DIR=$SHIPPABLE_REPO_DIR/shippable/testresults
    - CODE_COVERAGE_DIR=$SHIPPABLE_REPO_DIR/shippable/codecoverage
    - TESTS_LOC_DIR=$SHIPPABLE_REPO_DIR/tests
    - MOD_LOC=$SHIPPABLE_REPO_DIR/node_modules/.bin/
    - ECR_REPO=679404489841.dkr.ecr.us-east-1.amazonaws.com/deploy-ecs-multi-container

build:

  # http://docs.shippable.com/ci/shippableyml/#ci
  ci:
    # npm mirrors can sometimes be flacky, better to use shippable_retry
    # http://docs.shippable.com/ci/advancedOptions/retry/
    - shippable_retry npm install
    - mkdir -p $TEST_RESULTS_DIR && mkdir -p $CODE_COVERAGE_DIR
    - pushd $TESTS_LOC_DIR
    - $MOD_LOC/mocha --recursive "$TESTS_LOC_DIR/**/*.spec.js" -R mocha-junit-reporter --reporter-options mochaFile=$TEST_RESULTS_DIR/testresults.xml
    - $MOD_LOC/istanbul --include-all-sources cover -root "$SHIPPABLE_REPO_DIR/routes" $SHIPPABLE_REPO_DIR/node_modules/mocha/bin/_mocha -- -R spec-xunit-file --recursive "$TESTS_LOC_DIR/**/*.spec.js"
    - $MOD_LOC/istanbul report cobertura --dir $CODE_COVERAGE_DIR
    - popd

  # http://docs.shippable.com/ci/shippableyml/#post_ci
  post_ci:
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker build -t $ECR_REPO:$BRANCH.$BUILD_NUMBER .; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then docker push $ECR_REPO:$BRANCH.$BUILD_NUMBER ; fi'
    - 'if [ $IS_PULL_REQUEST == "false" ] ; then echo "versionName=$BRANCH.$BUILD_NUMBER" > $JOB_STATE/deploy-ecs-multi-container-image.env ; fi'

# Integrations are used to connect external resources to CI
# http://docs.shippable.com/integrations/overview/
integrations:
  # adding awsKeys integration so that credentials are available to CI Job
  # http://docs.shippable.com/platform/integration/aws-keys/
  hub:
    - integrationName: dr-aws-keys
      type: amazonKeys


resources:
  - name: deploy-ecs-multi-container-image
    type: image
    flags:
      - deploy-ecs-multi-container
    integration: dr-aws-keys
    pointer:
      sourceName: "679404489841.dkr.ecr.us-east-1.amazonaws.com/deploy-ecs-multi-container"
    seed:
      versionName: "latest"

  - name: deploy-ecs-multi-container-nginx
    type: image
    flags:
      - deploy-ecs-multi-container
    integration: dr-aws-keys
    pointer:
      sourceName: "679404489841.dkr.ecr.us-east-1.amazonaws.com/nginx"
    seed:
      versionName: "1.12.0"

  - name: deploy-ecs-multi-container-ecs-cluster
    type: cluster
    flags:
      - deploy-ecs-multi-container
    integration: dr-aws-keys
    pointer:
      sourceName : "deploy-ecs-basic" #name of the cluster to which we are deploying
      region: "us-east-1"


jobs:

  ###################################
  # runCI job to update the image tag
  ###################################
  - name: deploy-ecs-multi-container_runCI
    type: runCI
    flags:
      - deploy-ecs-multi-container
    steps:
      - OUT: deploy-ecs-multi-container-image

  ######################################
  # Two images, one manifest, one deploy
  ######################################

  - name: deploy-ecs-multi-container-manifest-1
    type: manifest
    flags:
      - deploy-ecs-multi-container
    steps:
     - IN: deploy-ecs-multi-container-image
     - IN: deploy-ecs-multi-container-nginx

  - name: deploy-ecs-multi-container-deploy-1
    type: deploy
    flags:
      - deploy-ecs-multi-container
    steps:
      - IN: deploy-ecs-multi-container-manifest-1
      - IN: deploy-ecs-multi-container-ecs-cluster


  ########################################
  # Two images, two manifests, one deploy
  ########################################

  - name: deploy-ecs-multi-container-manifest-2a
    type: manifest
    flags:
      - deploy-ecs-multi-container
    steps:
     - IN: deploy-ecs-multi-container-image

  - name: deploy-ecs-multi-container-manifest-2b
    type: manifest
    flags:
      - deploy-ecs-multi-container
    steps:
      - IN: deploy-ecs-multi-container-nginx

  - name: deploy-ecs-multi-container-deploy
    type: deploy
    flags:
      - deploy-ecs-multi-container
    workflow: parallel
    steps:
      - IN: deploy-ecs-multi-container-manifest-2a
      - IN: deploy-ecs-multi-container-manifest-2b
      - IN: deploy-ecs-multi-container-ecs-cluster

  ########################################
  # Two images, two manifests, two deploys
  ########################################

  - name: deploy-ecs-multi-container-manifest-3a
    type: manifest
    flags:
      - deploy-ecs-multi-container
    steps:
     - IN: deploy-ecs-multi-container-image

  - name: deploy-ecs-multi-container-manifest-3b
    type: manifest
    flags:
      - deploy-ecs-multi-container
    steps:
      - IN: deploy-ecs-multi-container-nginx

  - name: deploy-ecs-multi-container-deploy-3a
    type: deploy
    flags:
      - deploy-ecs-multi-container
    steps:
      - IN: deploy-ecs-multi-container-manifest-3a
      - IN: deploy-ecs-multi-container-ecs-cluster

  - name: deploy-ecs-multi-container-deploy-3b
    type: deploy
    flags:
      - deploy-ecs-multi-container
    steps:
      - IN: deploy-ecs-multi-container-manifest-3b
      - IN: deploy-ecs-multi-container-ecs-cluster
